# Generated by Django 3.1.5 on 2021-12-26 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PCS_system', '0002_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_type', models.CharField(max_length=100)),
            ],
        ),
    ]
