# Generated by Django 3.1.5 on 2021-12-26 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PCS_system', '0005_auto_20211226_1741'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
