# Generated by Django 3.1.5 on 2021-12-26 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PCS_system', '0007_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='user_id',
            new_name='student',
        ),
    ]
