# Generated by Django 3.1.5 on 2021-12-26 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PCS_system', '0008_auto_20211226_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='student',
        ),
        migrations.AddField(
            model_name='project',
            name='user_id',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='PCS_system.student'),
        ),
    ]
