# Generated by Django 3.1.5 on 2022-01-02 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PCS_system', '0010_auto_20220102_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='user_image',
            field=models.CharField(default='user_default.png', max_length=50),
        ),
    ]
