# Generated by Django 3.1.5 on 2022-01-04 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PCS_system', '0013_auto_20220105_0109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='role_id',
        ),
    ]
