# Generated by Django 3.1.5 on 2022-01-04 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PCS_system', '0014_remove_permission_role_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Permission',
        ),
        migrations.RemoveField(
            model_name='student',
            name='role_id',
        ),
    ]
