# Generated by Django 3.1.5 on 2022-01-04 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PCS_system', '0017_auto_20220105_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='role_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='PCS_system.role'),
        ),
    ]
