# Generated by Django 3.1.5 on 2022-01-07 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PCS_system', '0018_auto_20220105_0120'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(default='1', max_length=50),
        ),
    ]
