# Generated by Django 3.1.5 on 2022-01-09 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PCS_system', '0019_student_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_partners',
            field=models.CharField(max_length=45),
        ),
        migrations.CreateModel(
            name='Role_Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='PCS_system.permission')),
                ('role_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='PCS_system.role')),
            ],
        ),
    ]
