# Generated by Django 3.1.5 on 2022-01-09 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PCS_system', '0020_auto_20220109_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='role_id',
        ),
    ]
