# Generated by Django 3.1.5 on 2022-01-10 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PCS_system', '0021_remove_permission_role_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_points', models.CharField(max_length=500)),
            ],
        ),
    ]
